proxy: 'localhost:20171' # 本地代理
apiKey: ''
secretKey: ''
hotkey: #快捷键
  sale:
    - 'a' # 1
    - 's'
    - 'd'
    - 'f'
    - 'g'
    - 'h'
    - 'j'
    - 'k'
    - 'l'
    - ';'
    - 'z'
    - 'x'
    - 'c'
    - 'v'
    - 'b'
    - 'n'
    - 'm'
    - ','
    - '.'
    - '/' # 20
  buy:
    - '1' # 1
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - 'q'
    - 'w'
    - 'e'
    - 'r'
    - 't'
    - 'y'
    - 'u'
    - 'i'
    - 'o'
    - 'p' #20
